name: build
on: pull_request
jobs:
  build-and-test:
    strategy:
      matrix:
        go-version: [~1.17, ^1]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/cache@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: download go modules
        run: go mod download
      # - name: test
      #   run: TODO
      - name: build
        run: |
          mkdir -p build
          go build -o build/ks main.go