name: lint
on: [push, pull_request]

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci-lint
        uses: golangci/golangci-lint-action@v2