name: lint
on:
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci-lint
        uses: golangci/golangci-lint-action@v2